name = "dni-article-checker"
main = "./cloudflare-worker/index.ts"
compatibility_date = "2024-01-14"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "PR_STATE", id = "6e833b4dffaa41ef925cde46f134f928" }
]

[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm install"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

# Secrets that need to be set using `wrangler secret put`:
# - PAT_TOKEN
# - WEBHOOK_SECRET
# - CLAUDE_API_KEY 