name = "dni-article-checker"
main = "src/index.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat_v2"]

# KV Namespace for state management
[[kv_namespaces]]
binding = "PR_STATE"
id = "PR_STATE_ID" # You'll need to replace this with actual KV namespace ID

# Queue for processing jobs
[[queues.producers]]
binding = "PR_QUEUE"
queue = "pr-processing-queue"

[[queues.consumers]]
queue = "pr-processing-queue"
max_batch_size = 10
max_batch_timeout = 30

# Environment variables
[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm install"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

# Secrets that need to be set using `wrangler secret put`:
# - GITHUB_TOKEN
# - WEBHOOK_SECRET
# - CLAUDE_API_KEY
# - BRAVE_SEARCH_API_KEY 